### ISSUE TITLE
How to deploy Diamond that pass object as constructor argument in forge create

### ISSUE THREAD

**Issue by sunny0714** [FydeTreasury/Diamond-Foundry#2]
Hi @rsundar @Teamo0 
Have you tried to deploy this repo by using forge create?

https://ethereum.stackexchange.com/questions/140562/how-to-pass-object-as-constructor-arguments-to-a-contract-when-using-forge-creat
https://github.com/sunny0714/periphery-contracts

Please help me with this
Best

**Comment by Teamo0** [comment]
Hey @sunny0714,
I saw you already found the solution for your question regarding forge create. For deploying a diamond or in general multiple contracts it is more convenient to write a deploy script, where you can execute all the logic in one go.
We have added a deploy script for the standard facets and the diamond. It can be found in the 'script' directory. 
Hope that helps!

**Comment by sunny0714** [comment]
Hey @Teamo0 Yeah, the deployment script written by solidity is really helpful 💯 
And think that this repo will be perfect if includes verifying script as well
Cheers
