### ISSUE TITLE
Turning on RUST_LOG=forge causes generateSelectors to fail

### ISSUE THREAD

**Issue by jdbertron** [FydeTreasury/Diamond-Foundry#5]
The invocation of forge inspect <facet> methods  inherits the RUST_LOG=forge environment , which causes the parsing to fail. 
This means the RUST_LOG=forge debugging can't be used with this diamond. 
I tried passing cmd[0] = "RUST_LOG="  to see if it would null out the setting for that invocation, but it didn't work.

**Comment by rsundar** [comment]
Closing this since this PR https://github.com/FydeTreasury/Diamond-Foundry/pull/6 by @jdbertron solves this issue
